name = "news-app"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "bash build.sh"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

# تكوين Pages
[pages_build_output_dir]
value = "dist"
